
# Based on: https://zartman.xyz/blog/gh-static-deploy/
name: Server Deployment
on:
  push:
    branches:
      - main

env:
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
  CDA_HOST_NAME: tueicda-cda.srv.mwn.de
  CDA_USER_NAME: web-user
  CDA_TARGET_DIR: /var/www/cda/app/mqtbench/
  CDA_TARGET_DIR_FILES: /local/mqtbench/qasm_output
  CDA_SOURCE_DIR_FILES: benchviewer/static/files/qasm_output
  CDA_GIT_DIR: .git/

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Creating zip file
      run:  zip -rjv ./benchviewer/static/files/qasm_output/MQTBench_all.zip ./benchviewer/static/files/qasm_output/ ./benchviewer/static/files/algo_level.txt
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install wheel
      run: pip install wheel
    - name: Install MQT Bench
      run: pip install .\[all\]
    - name: Run tests
      run: |
        pip install pytest-cov
        pytest -v
    - name: Setup SSH via the stored Action Secrets
      run: |
        mkdir -p ~/.ssh
        echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
        echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
        echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
        chmod -R 700 ~/.ssh
    - name: rsync deployment
      working-directory: ${{ github.workspace }}
      run: |
        rsync -avz --update -e ssh ${CDA_SOURCE_DIR_FILES}/MQTBench_all.zip ${CDA_USER_NAME}@${CDA_HOST_NAME}:${CDA_TARGET_DIR_FILES}/MQTBench_all.zip
        rsync -avz --update -e ssh config.json ${CDA_USER_NAME}@${CDA_HOST_NAME}:${CDA_TARGET_DIR}/config.json
        rsync -avz --update -e ssh --cvs-exclude --exclude "*__pycache__/" --exclude "*.qasm" --exclude ${CDA_SOURCE_DIR_FILES} ./benchviewer ${CDA_USER_NAME}@${CDA_HOST_NAME}:${CDA_TARGET_DIR}

